export const DATA_REQUESTED = "DATA_REQUESTED";
export const DATA_LOADED = "DATA_LOADED";
export const API_ERRORED = "API_ERRORED";
export const GEN_MNEMONIC = "GEN_MNEMONIC";
export const ADD_MNEMONIC = "ADD_MNEMONIC";
export const FOUND_ERROR = "FOUND_ERROR";
export const DISMISS_TELEGRAM = "DISMISS_TELEGRAM";
